### ISSUE TITLE
Имена файлов

### ISSUE THREAD

**Issue by avasyukov** [Beloklokov101/AVL_tree_Beloklokov#2]
Исходники на C++ всё-таки очень принято именовать с расширением .cpp (сейчас расширения у файлов нет совсем).

**Comment by PBeloklokov** [comment]
Вы имеете в виду прикреплять задание в виде файлов с расширением .cpp или у меня где-то указано другое расширение? Если я не ошибаюсь, я все разы весь код не задумываясь просто копировал на гитхаб

**Comment by avasyukov** [comment]
Сейчас не указано никакое расширение. Создан файлик tree_like_a_class (без расширения), в него скопирован код. Код корректен. Но файл с исходниками без расширения - не фэн-шуйно. План-минимум - создать руками файл с корректным именем. План-максимум - уйти от копирования кода руками, использовать любой git-клиент, который будет синкать локальную папку проекта.

**Comment by PBeloklokov** [comment]
План минимум, возможно, выполнен, план максимум я, если не ошибаюсь, когда-то пытался выполнить, если вы имеете в виду работу с гитом через командную строку, но тогда почему-то не получилось плюс не сильно хотел, так что еще буду пробовать. Но временное решение с .cpp пока сделал

**Comment by avasyukov** [comment]
Подтверждаю, решено.

// Совсем по хорошему и лишние файлы нужно из репозитория убрать.
// Но финальный фэн-шуй всё равно ещё наводить позже.

// Ну и общаться с git-ом не обязательно через командную строку.
// Графический клиент в духе GitHub Desktop или GitKraken вполне ок.
