### ISSUE TITLE
Интерфейс и реализация

### ISSUE THREAD

**Issue by avasyukov** [Beloklokov101/AVL_tree_Beloklokov#3]
// Это должно было быть в тикете #1, но что-то я на тот момент просмотрел.

Сейчас интерфейс был поправлен. Конкретно в него были добавлены эти строки:
https://github.com/Beloklokov101/AVL_tree_Beloklokov/blob/2f2f4b419c38a248eb8e4c626cd0cdd45b390277/tree_file.cpp#L14-L15

Это нужно перенести в реализацию (в свой класс).

Причины:
- Интерфейс - это таки полностью абстрактный класс. В этом его фича - вы берёте свою реализацию интерфейса и реализацию кого-нибудь из товарищей, и можете подсунуть вызывающему коду (условному main-у) любую из них, и он не заметит переключения. Как только в *интерфейсе* оказались части *реализации* - всё, так сделать уже невозможно.
- Именно в силу такой роли интерфейсов в живом проекте в реальной жизни физически не будет возможности что-нибудь дописать в интерфейс. Он есть такой, какой есть, ничего в его сигнатуре изменить невозможно.

**Comment by PBeloklokov** [comment]
Все понял, исправил. Почему-то казалось, что реализация интерфейса на лмс была представлена предыдущим образом.

**Comment by avasyukov** [comment]
Подтверждаю, решено.
